language: java
jdk:
- oraclejdk8
services:
- postgresql
before_script:
- psql -c 'create database friendly_money_grinder;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: VDNMz6P5dMVIg/ixKucAU6v1+ZboGs21e5PBAVjQnc3XAqOcL53HdBucWllILwnjy0QTIZIij1skfSGzEFr7KLqO2sGmC7SLcuvZfSN0frcQ7Ia4dyNZHs1pbQy9gP+T3UMhF/ZQASgXpoJJ/HGNMNPZNJRciEMTMEjibA0TqSGpljeJMHMp2sFKuZokTzfL7lr+3wAgwZnpZAE9FtB2Wt84Gi7X6YNbOHbtjxTQytYqJlS9OAv2n3588WTpuKlidqYZu6jp2AugQp30o0ZvbSX9cS9FyISvMN0YJ61i5kpHg9irN6lIdpn1og0YOkMEqcQwmV7/oUxqJxEsrbYm6KoA9uyVuYjiPWUCAHssj1/adH/NfOKOhiatEozQlPageoCkAoeDEKowsT438F4xshEK+y2kGYrO/cA1XmkngWZJRakeg4tPzxcFf+VrcCCLQR0pcgVajZbddMuEG6zqD22yC0WWvzwiHljSE8bJFfa8RTTMtt/R60aTy6zl/+aAjpTEhmDdwoGa1wyUOFqq19i2ZfbmCMLevh28TpiUXdw8rexqH+ATZvPtIxDzuBVyG86ZHNwaYt1HPVK4l1IoDNZvOH0A7lgx1Qc1js3iXT24o2dVBlOpXcq48Or8jxWgbvtmrMF4YXZh1LzjZZRzuwz8+OYLUvz3Uth039aFRic=
  app: friendly-money-grinder