sudo: required

language: java

jdk:
- oraclejdk8

services:
- docker
- postgresql

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t myproject .
  - docker tag myproject $DOCKER_USERNAME/friendly-money-grinder
  - docker push $DOCKER_USERNAME/friendly-money-grinder

deploy:
  provider: heroku
  api_key:
    secure: KMqcLjEQ6MQY2Rnsg0iVsORFWAnfEDTkwmvM8MnYoi6vpCQVtIcoz4OMrwIp59j211i6BCapAOH++g7Rr0d/10HOCkAU9DFSVsG3PSt9fXZNkA18RQX8dLAO5wUsr1hUjokDk8LysovjRzAHI0GZT++VibFK9+bc7W8ZCuKxTV4ZCRbRd9HTEroXKU4wkUE9Z8XAxlTqYsm/sgf9KxSWZlxOFHb7+y2XxHCu9F5V+mxBromg5nQBKWN38aNQq/Dup7n6kLzOdZ2D/oUTaD0afk+0N6VQEbSKJWFohGkKYonCJM6ygG9KFmQ99MA+bockyLN4mNg06Eb7VhpriUKdWwFtZov3tgTQtVtvkEhX2HvfbhAEJ3DWX+ZIOzaH6Tw3aoH++vzruJmsbPrlMlJUZbZx01CXDur0nmFK8JOwQ+bnf0nTTJQNG1nuJq/FbIw+iVlYrrhVgvEo7fuIKpvKi0KhdpsTHX4y7/Jhz1eJvZvQbow0oHB/4qpHbRTpVOTty+djN25abQWKpMati6f8YiwJLOsCMxNgsW6uuBgq2nQhD3Yr/0fSZKYqbcPSrai/kH3h2opE70vVIw29KG2b6gfPqUWbTmK2jxRSfqUYsSYfLKl/x6ka17sBtyD3fR9ID1G1bvYjB3Ajre47UbdQChmXz84pA41SrdV6Rw2kiQk=
  app: friendly-money-grinder
